- name: Install CUPS and helpers
  apt:
    name:
      - cups
      - avahi-daemon
      - ipp-usb
    state: present
    update_cache: yes

- name: Enable and start CUPS
  systemd:
    name: cups
    state: started
    enabled: yes

- name: Allow remote admin (optional)
  command: cupsctl --remote-admin --remote-any --share-printers
  changed_when: false

- name: Set default print options (disable duplex)
  command: lpoptions -p mp-brother -o sides=one-sided -o media=A4
  become: yes
