- hosts: printpi
  become: yes
  vars:
    GATEWAY_ID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    API_KEY: "pgw_CHANGEME"
    WS_URL: "wss://printgateway.toorren.nl/ws/gateway"
    PRINTER_NAME: "PRINTERNAAM"
  roles:
    - cups
    - printbot
